### ISSUE TITLE
installation on windows

### ISSUE THREAD

**Issue by madhudharmav** [jcrudy/py-earth#61]
Hi,

I find it hard to install this package in windows.
I have anaconda ,numpy installed and cygwin installed.
the installations stalls with "c:\....\gcc.exe failed with exit status 1"

thanks 
Madhu

**Comment by jcrudy** [comment]
Thanks for the report.  Can you provide more details?  In particular, exactly how are you installing and is there any other output before the error message?  Also, are you able to install any other cython or C based python packages?  If you're not sure, you could try installing choldate from my giithub (https://github.com/jcrudy/choldate) and see if it works.  You need to have cython installed for that one.

**Comment by sschnug** [comment]
It looks, that your cygwin installation isn't working/set up correctly. This may be complicated because you do have to tell python where your compilation tools are. This is normally done like described here [StackOverflow-Question](http://stackoverflow.com/questions/3297254/how-to-use-mingws-gcc-compiler-when-installing-python-package-using-pip). I can't tell you, if cygwin is even possible or recommended (mingw seems to be more appropriate).

Another recommended solution/setup i recommend (i'm glad your already using anaconda):
- Install anaconda/miniconda (in your case: done!)
- Use conda to install libpython (which has a MingW dependency) 
- (maybe set the PATH to gcc which was created in last step -> Miniconda/MingW ?

This allowed me to "install" py-earth without problems, BUT:
-  While running the example, the following happens:
 - `ImportError: No module named _forward`

Now i have to understand what is happening and maybe i need to search for an similar issue (or create a new one)

**Comment by madhudharmav** [comment]
Sorry for my late feedback.
I tried the installation with sschnugs suggestions and it worked like magic. The problem seems to be that the gcc accessed (from Rtools in my case ).Changing the path to mingw solved the problem.

thanks & cheers

**Comment by jcrudy** [comment]
@madhudharmav I'm glad that's cleared up.  Thank you, @sschnug, for your help.  I'm going to close this issue.  @sschnug, if you are still having the import problem with ipython notebook, will you please open a new issue?  I tried the example in ipython notebook under anaconda on my macbook, and it worked fine for me, so please include as much info as possible about the error and your system so I can try to figure out what's going on.

-Jason
