### ISSUE TITLE
What is the latest update on this in Scikitlearn 

### ISSUE THREAD

**Issue by springcoil** [jcrudy/py-earth#94]
I understood that there was a project to integrate this into scikitlearn. What's the status?

**Comment by jcrudy** [comment]
@springcoil Yes, that's correct.  However, I think the current consensus is that py-earth will become a sklearn contrib project.  See link below.  I am of course interested in other opinions, though.  The reason contrib seems like the right choice is that py-earth would still get some additional exposure and development attention without the effort and delays involved in full integration.  It also allows py-earth to keep some of its more useful incompatibilities, such as `predict_deriv` and the handling of dataframes and missingness, without needing to figure out exactly how those fit into scikit-learn.

Currently, @mehdidc is working on meeting contrib requirements.  He may have additional comments on this issue.  I'm going to close in order to keep the issues list clean(er), but feel free to comment further.

https://github.com/scikit-learn-contrib
